# Generated by Django 5.0.4 on 2024-05-15 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallRequestHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('group_name', models.CharField(default='', max_length=255, verbose_name='group name')),
                ('responsible_person', models.CharField(default='', max_length=50, verbose_name='responsible person')),
                ('address', models.CharField(default='', max_length=255, verbose_name='responsible person')),
                ('phone_number', models.CharField(default='', max_length=50, verbose_name='phone number')),
                ('email_adress', models.CharField(default='', max_length=255, verbose_name='phone number')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='reson')),
                ('start_datetime', models.DateTimeField(verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end datetime')),
                ('room', models.CharField(choices=[('1', 'Big Room'), ('2', 'Japanese Style Room'), ('3', 'Neighborhood hall 2F')], default='1', max_length=1, verbose_name='room')),
                ('detail', models.CharField(default='', max_length=255, verbose_name='detail')),
                ('note', models.TextField(default='', verbose_name='note')),
            ],
            options={
                'verbose_name': 'Hall Request History',
                'verbose_name_plural': 'Hall Request History',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='rulebookmodel',
            name='document',
            field=models.FileField(upload_to='rule', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF'),
        ),
    ]
