# Generated by Django 5.0.4 on 2024-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_hallrequesthistorymodel_alter_rulebookmodel_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallrequesthistorymodel',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='is finished'),
        ),
    ]
