# Generated by Django 5.0.4 on 2024-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_hallrequestreceivermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallrequesthistorymodel',
            name='email_adress',
        ),
        migrations.AddField(
            model_name='hallrequesthistorymodel',
            name='email_address',
            field=models.CharField(default='', max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='hallrequesthistorymodel',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
        ),
    ]
