# Generated by Django 5.0.4 on 2024-05-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_hallrequesthistorymodel_email_adress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HallRequestHistoryModel',
            new_name='HallRequestModel',
        ),
        migrations.AlterModelOptions(
            name='hallrequestmodel',
            options={'ordering': ['created_at'], 'verbose_name': 'Hall Request', 'verbose_name_plural': 'Hall Request'},
        ),
    ]
