# Generated by Django 5.0.4 on 2024-05-24 10:20

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_rename_hallrequesthistorymodel_hallrequestmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyQuetionAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('status', models.CharField(choices=[('1', 'draft'), ('2', 'publish')], default='1', help_text='下書きを選択すると、サイトの管理ユーザーのみが見られる状態になります。', max_length=1, verbose_name='status')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text='公開を選択すると、ここで設定した日時までは公開されません', null=True, verbose_name='publish date')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='公開を選択すると、ここで設定した日時以降は公開されません', null=True, verbose_name='expiry date')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='answer')),
                ('sortid', models.IntegerField(db_index=True, default=0, help_text='サイトで昇順に並びます', verbose_name=' ')),
                ('created_by', models.ForeignKey(db_column='created_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('modified_by', models.ForeignKey(db_column='modified_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified_by')),
            ],
            options={
                'verbose_name': 'Frequently Quetion Answer',
                'verbose_name_plural': 'Frequently Quetion Answer',
                'ordering': ['sortid'],
            },
        ),
    ]
