# Generated by Django 5.0.4 on 2024-05-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_frequentlyquetionanswermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('status', models.IntegerField(choices=[('1', 'untreated'), ('2', 'confirmed'), ('3', 'finished')], default='1', verbose_name='query status')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='mail address')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
            ],
            options={
                'verbose_name': 'inquiries',
                'verbose_name_plural': 'inquiries',
            },
        ),
        migrations.AlterField(
            model_name='frequentlyquetionanswermodel',
            name='sortid',
            field=models.IntegerField(db_index=True, default=0, help_text='サイトで昇順に並びます', verbose_name='sort'),
        ),
    ]
