# Generated by Django 5.0.4 on 2024-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_rulepagemodel_options_queryreceivermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='status',
            field=models.CharField(choices=[('1', 'untreated'), ('2', 'confirmed'), ('3', 'finished')], default='1', max_length=1, verbose_name='query status'),
        ),
    ]
