// Modals
export const MODAL_HALL_REQUEST_CONFIRM_OPEN  = "MODAL_HALL_REQUEST_CONFIRM_OPEN";
export const MODAL_HALL_REQUEST_CONFIRM_CLOSE = "MODAL_HALL_REQUEST_CONFIRM_CLOSE";
export const MODAL_QUERY_CONFIRM_OPEN         = "MODAL_QUERY_CONFIRM_OPEN";
export const MODAL_QUERY_CONFIRM_CLOSE        = "MODAL_QUERY_CONFIRM_CLOSE";

// Boards
export const BOARD_YEAR  = "BOARD_YEAR";
export const BOARD_MODELS  = "BOARD_MODELS";

// Activity
export const ACTIVITY_YEAR  = "ACTIVITY_YEAR";
export const ACTIVITY_MODELS  = "ACTIVITY_MODELS";
