# Generated by Django 5.1.3 on 2025-01-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'confirmed'), (2, 'tentative'), (3, 'cancelled')], default=1)),
            ],
        ),
    ]
