# Generated by Django 5.1.3 on 2025-01-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_halleventmodel_created_halleventmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halleventmodel',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
