# Generated by Django 5.1.3 on 2025-01-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_halleventmodel_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'confirmed'), (2, 'tentative'), (3, 'cancelled')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MainEventManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'confirmed'), (2, 'tentative'), (3, 'cancelled')], default=1)),
            ],
        ),
    ]
