# Generated by Django 5.1.3 on 2025-01-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_garbageeventmodel_maineventmanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainEventManager',
            new_name='MainEventModel',
        ),
    ]
