# Generated by Django 5.0.4 on 2024-04-30 05:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='8文字以内', max_length=8, unique=True, verbose_name='カテゴリー名')),
                ('fgcolor', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='文字色')),
                ('bgcolor', colorfield.fields.ColorField(default='#ff0000', image_field=None, max_length=25, samples=None, verbose_name='背景色')),
                ('sortid', models.IntegerField(db_index=True, default=0, help_text='サイトで昇順に並びます', verbose_name=' ')),
            ],
            options={
                'verbose_name': 'お知らせカテゴリー',
                'verbose_name_plural': 'お知らせカテゴリー',
                'ordering': ['sortid'],
            },
        ),
    ]
