# Generated by Django 5.0.4 on 2024-05-04 12:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategorymodel',
            options={'ordering': ['sortid'], 'verbose_name': 'news category', 'verbose_name_plural': 'news category'},
        ),
        migrations.AlterField(
            model_name='newscategorymodel',
            name='bgcolor',
            field=colorfield.fields.ColorField(default='#ff0000', image_field=None, max_length=25, samples=None, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='newscategorymodel',
            name='fgcolor',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='foreground color'),
        ),
        migrations.AlterField(
            model_name='newscategorymodel',
            name='name',
            field=models.CharField(help_text='8文字以内', max_length=8, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='newscategorymodel',
            name='sortid',
            field=models.IntegerField(db_index=True, default=0, help_text='sort by ascending', verbose_name='sort key'),
        ),
    ]
