# Generated by Django 5.0.4 on 2024-05-04 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_alter_newscategorymodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('status', models.CharField(choices=[('1', 'draft'), ('2', 'publish')], default='1', help_text='下書きを選択すると、サイトの管理ユーザーのみが見られる状態になります。', max_length=1, verbose_name='status')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text='公開を選択すると、ここで設定した日時までは公開されません', null=True, verbose_name='publish date')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='公開を選択すると、ここで設定した日時以降は公開されません', null=True, verbose_name='expiry date')),
                ('title', models.CharField(default='', help_text='news title', max_length=200, verbose_name='title')),
                ('url', models.URLField(help_text='url', verbose_name='URL')),
                ('category', models.ForeignKey(help_text='news category', on_delete=django.db.models.deletion.CASCADE, to='publish.newscategorymodel', verbose_name='category')),
                ('created_by', models.ForeignKey(db_column='created_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('modified_by', models.ForeignKey(db_column='modified_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified_by')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
