# Generated by Django 5.0.4 on 2024-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='url',
            field=models.SlugField(help_text='/media/example.pdf', verbose_name='URL'),
        ),
    ]
