# Generated by Django 5.0.4 on 2024-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_alter_newsmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
