# Generated by Django 5.1.3 on 2025-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_alter_boardmodel_news_activitymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
